# Generated by Django 6.0 on 2025-12-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('unlock_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('family', 'Family'), ('public', 'Public')], default='private', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='capsules/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='capsules/videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='capsules/audio/')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collab_capsules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='received_capsules', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.theme')),
            ],
        ),
    ]
