# Generated by Django 6.0 on 2025-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_capsulecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulecomment',
            name='reaction',
            field=models.CharField(blank=True, choices=[('❤️', '❤️'), ('👍', '👍'), ('😢', '😢')], max_length=2),
        ),
    ]
