# Generated by Django 6.0 on 2025-12-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_capsulecomment_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='capsules/entries/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='capsules/entries/videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='capsules/entries/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.capsule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
