# Generated by Django 6.0 on 2025-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_capsuleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='event_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capsule',
            name='unlock_event',
            field=models.CharField(blank=True, choices=[('graduation', 'Graduation'), ('wedding', 'Wedding'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('custom', 'Custom Event')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='unlock_type',
            field=models.CharField(choices=[('date', 'Date'), ('event', 'Life Event')], default='date', max_length=20),
        ),
    ]
