# Generated by Django 6.0 on 2025-12-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
