# Generated by Django 6.0 on 2025-12-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_capsule_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.theme'),
        ),
    ]
